service: ecom-be
frameworkVersion: '3.38.0'

provider:
  name: aws
  runtime: nodejs18.x
  region: ${env:AWS_REGION}
  environment:
    MONGODB_URI: ${env:MONGODB_URI}
    NODE_ENV: production

functions:
  api:
    handler: index.handler
    events:
      - http:
          path: /{proxy+}
          method: ANY
          cors: true

  websocketConnect:
    handler: services/websocket.handleConnect
    events:
      - websocket:
          route: $connect

  websocketDisconnect:
    handler: services/websocket.handleDisconnect
    events:
      - websocket:
          route: $disconnect

  websocketMessage:
    handler: services/websocket.handleMessage
    events:
      - websocket:
          route: $default

resources:
  Resources:
    WebSocketConnections:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: WebSocketConnections
        AttributeDefinitions:
          - AttributeName: connectionId
            AttributeType: S
        KeySchema:
          - AttributeName: connectionId
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST

plugins:
  - serverless-offline